import { v4 as uuid } from "uuid";
import { db, migrate } from "./db";
import type { Property } from "../types";

const properties: Array<Omit<Property, "id" | "createdAt">> = [
  {
    title: "Sunrise Meadows 3BHK",
    propertyType: "apartment",
    city: "Pune",
    state: "Maharashtra",
    locality: "Baner",
    priceInr: 11500000,
    bhk: 3,
    areaSqft: 1450,
    amenities: ["clubhouse", "swimming pool", "gym", "power backup", "covered parking"],
    imageUrl: "https://images.example.com/properties/sunrise-meadows.jpg",
    listingUrl: "https://yourrealtysite.com/listing/sunrise-meadows-baner-pune",
    description: "Spacious 3BHK in a gated township close to Baner IT hub, ready to move in.",
  },
  {
    title: "Lakeview Residency 2BHK",
    propertyType: "apartment",
    city: "Pune",
    state: "Maharashtra",
    locality: "Wakad",
    priceInr: 7800000,
    bhk: 2,
    areaSqft: 980,
    amenities: ["lift", "children's play area", "24x7 security"],
    imageUrl: "https://images.example.com/properties/lakeview-residency.jpg",
    listingUrl: "https://yourrealtysite.com/listing/lakeview-residency-wakad-pune",
    description: "Affordable 2BHK near Hinjewadi IT park, great for young families.",
  },
  {
    title: "Palm Grove Villa",
    propertyType: "villa",
    city: "Pune",
    state: "Maharashtra",
    locality: "Kondhwa",
    priceInr: 24500000,
    bhk: 4,
    areaSqft: 3200,
    amenities: ["private garden", "servant room", "modular kitchen", "3 car parking"],
    imageUrl: "https://images.example.com/properties/palm-grove-villa.jpg",
    listingUrl: "https://yourrealtysite.com/listing/palm-grove-villa-kondhwa-pune",
    description: "Independent villa with private garden in a quiet, well-connected locality.",
  },
  {
    title: "Marine Heights 2BHK Sea Facing",
    propertyType: "apartment",
    city: "Mumbai",
    state: "Maharashtra",
    locality: "Andheri West",
    priceInr: 21000000,
    bhk: 2,
    areaSqft: 850,
    amenities: ["sea view", "gym", "lift", "metro nearby"],
    imageUrl: "https://images.example.com/properties/marine-heights.jpg",
    listingUrl: "https://yourrealtysite.com/listing/marine-heights-andheri-mumbai",
    description: "Sea-facing 2BHK in the heart of Andheri West, walk to metro station.",
  },
  {
    title: "Thane Green Enclave 1BHK",
    propertyType: "apartment",
    city: "Thane",
    state: "Maharashtra",
    locality: "Ghodbunder Road",
    priceInr: 5200000,
    bhk: 1,
    areaSqft: 620,
    amenities: ["clubhouse", "jogging track", "power backup"],
    imageUrl: "https://images.example.com/properties/thane-green-enclave.jpg",
    listingUrl: "https://yourrealtysite.com/listing/thane-green-enclave-ghodbunder",
    description: "Budget-friendly 1BHK in a rapidly developing suburb with great connectivity.",
  },
  {
    title: "Whitefield Tech Homes 3BHK",
    propertyType: "apartment",
    city: "Bangalore",
    state: "Karnataka",
    locality: "Whitefield",
    priceInr: 9800000,
    bhk: 3,
    areaSqft: 1550,
    amenities: ["clubhouse", "swimming pool", "co-working lounge", "EV charging"],
    imageUrl: "https://images.example.com/properties/whitefield-tech-homes.jpg",
    listingUrl: "https://yourrealtysite.com/listing/whitefield-tech-homes-bangalore",
    description: "Modern 3BHK minutes from ITPL, ideal for IT professionals.",
  },
  {
    title: "Electronic City Studio Apartments",
    propertyType: "apartment",
    city: "Bangalore",
    state: "Karnataka",
    locality: "Electronic City",
    priceInr: 4300000,
    bhk: 1,
    areaSqft: 540,
    amenities: ["gym", "lift", "24x7 water supply"],
    imageUrl: "https://images.example.com/properties/electronic-city-studio.jpg",
    listingUrl: "https://yourrealtysite.com/listing/electronic-city-studio-bangalore",
    description: "Compact 1BHK close to Electronic City Phase 1, great rental yield.",
  },
  {
    title: "Sarjapur Luxury Villa",
    propertyType: "villa",
    city: "Bangalore",
    state: "Karnataka",
    locality: "Sarjapur Road",
    priceInr: 32000000,
    bhk: 4,
    areaSqft: 3600,
    amenities: ["private pool", "home theatre", "landscaped garden", "smart home"],
    imageUrl: "https://images.example.com/properties/sarjapur-luxury-villa.jpg",
    listingUrl: "https://yourrealtysite.com/listing/sarjapur-luxury-villa-bangalore",
    description: "Ultra-premium villa in a gated community popular with senior tech executives.",
  },
  {
    title: "HSR Layout Commercial Office Space",
    propertyType: "commercial",
    city: "Bangalore",
    state: "Karnataka",
    locality: "HSR Layout",
    priceInr: 18500000,
    bhk: null,
    areaSqft: 2000,
    amenities: ["central AC", "parking", "high-speed lift", "food court nearby"],
    imageUrl: "https://images.example.com/properties/hsr-commercial.jpg",
    listingUrl: "https://yourrealtysite.com/listing/hsr-layout-office-bangalore",
    description: "Grade-A office space suited for startups and corporate branch offices.",
  },
  {
    title: "Gachibowli Skyline 3BHK",
    propertyType: "apartment",
    city: "Hyderabad",
    state: "Telangana",
    locality: "Gachibowli",
    priceInr: 10800000,
    bhk: 3,
    areaSqft: 1600,
    amenities: ["clubhouse", "swimming pool", "indoor games", "gym"],
    imageUrl: "https://images.example.com/properties/gachibowli-skyline.jpg",
    listingUrl: "https://yourrealtysite.com/listing/gachibowli-skyline-hyderabad",
    description: "Premium 3BHK close to the financial district, popular with IT families.",
  },
  {
    title: "Kondapur Compact 2BHK",
    propertyType: "apartment",
    city: "Hyderabad",
    state: "Telangana",
    locality: "Kondapur",
    priceInr: 6500000,
    bhk: 2,
    areaSqft: 1050,
    amenities: ["lift", "power backup", "children's park"],
    imageUrl: "https://images.example.com/properties/kondapur-compact.jpg",
    listingUrl: "https://yourrealtysite.com/listing/kondapur-compact-hyderabad",
    description: "Well-priced 2BHK in a well-established, family-friendly neighbourhood.",
  },
  {
    title: "Shamshabad Farmland Plot",
    propertyType: "plot",
    city: "Hyderabad",
    state: "Telangana",
    locality: "Shamshabad",
    priceInr: 3200000,
    bhk: null,
    areaSqft: 2400,
    amenities: ["gated layout", "DTCP approved", "borewell"],
    imageUrl: "https://images.example.com/properties/shamshabad-plot.jpg",
    listingUrl: "https://yourrealtysite.com/listing/shamshabad-plot-hyderabad",
    description: "DTCP-approved residential plot near the airport expressway, great appreciation potential.",
  },
  {
    title: "OMR Tech Corridor 2BHK",
    propertyType: "apartment",
    city: "Chennai",
    state: "Tamil Nadu",
    locality: "OMR",
    priceInr: 6800000,
    bhk: 2,
    areaSqft: 1020,
    amenities: ["clubhouse", "gym", "24x7 security"],
    imageUrl: "https://images.example.com/properties/omr-tech-corridor.jpg",
    listingUrl: "https://yourrealtysite.com/listing/omr-tech-corridor-chennai",
    description: "Well-connected 2BHK along the IT corridor, close to major tech parks.",
  },
  {
    title: "Adyar Heritage 3BHK",
    propertyType: "apartment",
    city: "Chennai",
    state: "Tamil Nadu",
    locality: "Adyar",
    priceInr: 15500000,
    bhk: 3,
    areaSqft: 1700,
    amenities: ["covered parking", "generator backup", "close to schools"],
    imageUrl: "https://images.example.com/properties/adyar-heritage.jpg",
    listingUrl: "https://yourrealtysite.com/listing/adyar-heritage-chennai",
    description: "Elegant 3BHK in one of Chennai's most sought-after residential areas.",
  },
  {
    title: "Gurgaon Cyber Hub Suites",
    propertyType: "apartment",
    city: "Gurgaon",
    state: "Haryana",
    locality: "Sector 24",
    priceInr: 13200000,
    bhk: 3,
    areaSqft: 1580,
    amenities: ["clubhouse", "swimming pool", "gym", "metro nearby"],
    imageUrl: "https://images.example.com/properties/gurgaon-cyber-hub-suites.jpg",
    listingUrl: "https://yourrealtysite.com/listing/gurgaon-cyber-hub-suites",
    description: "Premium residence walking distance from Cyber Hub and Rapid Metro.",
  },
  {
    title: "Sohna Road Affordable 1BHK",
    propertyType: "apartment",
    city: "Gurgaon",
    state: "Haryana",
    locality: "Sohna Road",
    priceInr: 4100000,
    bhk: 1,
    areaSqft: 550,
    amenities: ["lift", "power backup", "gated community"],
    imageUrl: "https://images.example.com/properties/sohna-road-affordable.jpg",
    listingUrl: "https://yourrealtysite.com/listing/sohna-road-affordable-gurgaon",
    description: "Budget 1BHK ideal for first-time buyers and rental investment.",
  },
  {
    title: "Dwarka Expressway Independent House",
    propertyType: "independent_house",
    city: "Gurgaon",
    state: "Haryana",
    locality: "Dwarka Expressway",
    priceInr: 19500000,
    bhk: 4,
    areaSqft: 2700,
    amenities: ["private terrace", "modular kitchen", "4 car parking"],
    imageUrl: "https://images.example.com/properties/dwarka-expressway-house.jpg",
    listingUrl: "https://yourrealtysite.com/listing/dwarka-expressway-house-gurgaon",
    description: "Independent house on a rapidly developing expressway corridor.",
  },
  {
    title: "Rohini Sector 24 3BHK",
    propertyType: "apartment",
    city: "Delhi",
    state: "Delhi",
    locality: "Rohini",
    priceInr: 12500000,
    bhk: 3,
    areaSqft: 1350,
    amenities: ["lift", "power backup", "covered parking", "market nearby"],
    imageUrl: "https://images.example.com/properties/rohini-sector24.jpg",
    listingUrl: "https://yourrealtysite.com/listing/rohini-sector24-delhi",
    description: "Well-located 3BHK in North Delhi with excellent metro connectivity.",
  },
  {
    title: "Dwarka Sub City 2BHK",
    propertyType: "apartment",
    city: "Delhi",
    state: "Delhi",
    locality: "Dwarka",
    priceInr: 8900000,
    bhk: 2,
    areaSqft: 950,
    amenities: ["clubhouse", "lift", "24x7 security"],
    imageUrl: "https://images.example.com/properties/dwarka-sub-city.jpg",
    listingUrl: "https://yourrealtysite.com/listing/dwarka-sub-city-delhi",
    description: "Family-friendly 2BHK in a planned sub-city with wide roads and parks.",
  },
  {
    title: "Noida Sector 62 Tech PG",
    propertyType: "pg",
    city: "Noida",
    state: "Uttar Pradesh",
    locality: "Sector 62",
    priceInr: 15000,
    bhk: null,
    areaSqft: 180,
    amenities: ["wifi", "meals included", "AC", "laundry"],
    imageUrl: "https://images.example.com/properties/noida-sector62-pg.jpg",
    listingUrl: "https://yourrealtysite.com/listing/noida-sector62-pg",
    description: "Fully furnished PG for working professionals near the IT corridor (monthly rent shown).",
  },
  {
    title: "Noida Extension 2BHK",
    propertyType: "apartment",
    city: "Noida",
    state: "Uttar Pradesh",
    locality: "Noida Extension",
    priceInr: 5600000,
    bhk: 2,
    areaSqft: 900,
    amenities: ["clubhouse", "kids play area", "gym"],
    imageUrl: "https://images.example.com/properties/noida-extension-2bhk.jpg",
    listingUrl: "https://yourrealtysite.com/listing/noida-extension-2bhk",
    description: "Value-for-money 2BHK in a fast-growing residential belt.",
  },
  {
    title: "Kharadi Riverside 2BHK",
    propertyType: "apartment",
    city: "Pune",
    state: "Maharashtra",
    locality: "Kharadi",
    priceInr: 8600000,
    bhk: 2,
    areaSqft: 1000,
    amenities: ["riverside walkway", "clubhouse", "gym", "covered parking"],
    imageUrl: "https://images.example.com/properties/kharadi-riverside.jpg",
    listingUrl: "https://yourrealtysite.com/listing/kharadi-riverside-pune",
    description: "Contemporary 2BHK close to EON IT Park with riverside views.",
  },
  {
    title: "Indiranagar Boutique 2BHK",
    propertyType: "apartment",
    city: "Bangalore",
    state: "Karnataka",
    locality: "Indiranagar",
    priceInr: 16500000,
    bhk: 2,
    areaSqft: 1150,
    amenities: ["lift", "covered parking", "walk to metro", "cafes nearby"],
    imageUrl: "https://images.example.com/properties/indiranagar-boutique.jpg",
    listingUrl: "https://yourrealtysite.com/listing/indiranagar-boutique-bangalore",
    description: "Boutique residence in Bangalore's most vibrant, walkable neighbourhood.",
  },
  {
    title: "Wagholi Emerging Plot",
    propertyType: "plot",
    city: "Pune",
    state: "Maharashtra",
    locality: "Wagholi",
    priceInr: 2800000,
    bhk: null,
    areaSqft: 2000,
    amenities: ["gated layout", "clear title", "wide roads"],
    imageUrl: "https://images.example.com/properties/wagholi-plot.jpg",
    listingUrl: "https://yourrealtysite.com/listing/wagholi-plot-pune",
    description: "Residential plot in a rapidly appreciating eastern Pune suburb.",
  },
];

export function seedIfEmpty() {
  migrate();
  const count = (db.prepare("SELECT COUNT(*) as c FROM properties").get() as { c: number }).c;
  if (count > 0) {
    console.log(`Seed skipped: ${count} properties already exist. Delete data/realty.db to reseed.`);
    return;
  }

  const insert = db.prepare(`
    INSERT INTO properties
      (id, title, property_type, city, state, locality, price_inr, bhk, area_sqft, amenities, image_url, listing_url, description)
    VALUES
      (@id, @title, @propertyType, @city, @state, @locality, @priceInr, @bhk, @areaSqft, @amenities, @imageUrl, @listingUrl, @description)
  `);

  const insertMany = db.transaction((rows: Array<Omit<Property, "createdAt">>) => {
    for (const row of rows) {
      insert.run({ ...row, amenities: JSON.stringify(row.amenities) });
    }
  });

  insertMany(properties.map((p) => ({ ...p, id: uuid() })));
  console.log(`Seeded ${properties.length} properties.`);
}

if (require.main === module) {
  seedIfEmpty();
}
